### ISSUE TITLE
Automatic encoder selection failed Default encoder for format mp3

### ISSUE THREAD

**Issue by ufogxl** [kewlbear/FFmpeg-iOS#12]
`
            let result = ffmpeg(["ffmpeg", "-i", source.path, destination])
`

encountered an error while I was converting .m4a to .mp3:

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/private/var/mobile/Containers/Shared/AppGroup/1ECB4F4A-3F79-4E52-A290-78F4F12BAFF9/File Provider Storage/test.m4a':
  Metadata:
    major_brand     : M4A 
    minor_version   : 0
    compatible_brands: M4A isommp42
    creation_time   : 2020-06-03T13:20:08.000000Z
    iTunSMPB        :  00000000 00000840 0000039D 00000000005B3423 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    voice-memo-uuid : 3A3C853F-58D9-41C9-992B-106FD926A185
    encoder         : com.apple.VoiceMemos (iOS 13.4.1)
  Duration: 00:02:04.59, start: 0.044000, bitrate: 68 kb/s
  Stream #0:0[0x1](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, mono, fltp, 64 kb/s (default)
    Metadata:
      creation_time   : 2020-06-03T13:20:08.000000Z
      handler_name    : Core Media Audio
      vendor_id       : [0][0][0][0]
[aost#0:0 @ 0x10b83ab90] Automatic encoder selection failed Default encoder for format mp3 (codec mp3) is probably disabled. Please choose an encoder manually.
[aost#0:0 @ 0x10b83ab90] Error selecting an encoder

**Comment by kewlbear** [comment]
Try https://github.com/kewlbear/FFmpeg-iOS-Lame package which comes with mp3lame library.

**Comment by ufogxl** [comment]
> Try https://github.com/kewlbear/FFmpeg-iOS-Lame package which comes with mp3lame library.

solved my problem,thanks!
