### ISSUE TITLE
No such module 'avformat'

### ISSUE THREAD

**Issue by mvictor27** [kewlbear/FFmpeg-iOS#6]
Hi man, great work. Thanks for your time. 

I have some issue when I tray to import avformat I get this error "No such module 'avformat'".
Do I missed some steps?

**Comment by kewlbear** [comment]
How did you add the package? Also I've made some changes. Please try again after updating to latest version.

**Comment by mvictor27** [comment]
When I added it to a new sample app is working as expected. 
But I really want to add it as dependence in other Swift Package, and in that package I get this error "No such module 'avformat'".

**Comment by kewlbear** [comment]
Did you put "FFmpeg-iOS" to your Swift Package target's dependencies?  I just created a package to reproduce this issue, but it doesn't happen.  
<img width="1512" alt="스크린샷 2021-01-19 오전 8 33 56" src="https://user-images.githubusercontent.com/1168866/104971351-d944e380-5a31-11eb-8520-f2312761bed2.png">

**Comment by mvictor27** [comment]
Yes, I added it to Swift Package target's dependencies.

<img width="1499" alt="Screenshot 2021-01-19 at 09 06 00" src="https://user-images.githubusercontent.com/5881435/104999585-c59b7c00-5a35-11eb-90e2-3b96ddbe1882.png">

And this is my swift package: 
<img width="1499" alt="Screenshot 2021-01-19 at 09 08 20" src="https://user-images.githubusercontent.com/5881435/104999682-f085d000-5a35-11eb-8469-9fbf444e73a5.png">

And I don't understand what is wrong in my example.

**Comment by mvictor27** [comment]
I use Xcode version 12.3 (12C33), what version do you have ?

**Comment by kewlbear** [comment]
You need to add "FFmpeg-iOS" to `.target(name: "VideoFFmpeg", dependencies: [<here>])`.

**Comment by mvictor27** [comment]
Oh, thanks,  it works now
