### ISSUE TITLE
"Assertion failed: Expected 1 archs in otool output" at distribution stage

### ISSUE THREAD

**Issue by JonasVautherin** [kewlbear/FFmpeg-iOS#7]
In an open source project, we have [this example app](https://github.com/mavlink/mavsdk-swift-example) that depends on FFmpeg-iOS (see [here](https://github.com/mavlink/MAVSDK-Swift-Example/blob/master/project.yml#L13-L15)). First, thanks a lot for that :slightly_smiling_face:.

When going into the "distribution" stage of the app, the following error occurs:

```
2021-04-13 19:54:30 +0000  Assertion failed: Expected 1 archs in otool output:
Archive : /var/folders/fk/9kh981v9165g2t1yh3lbrkcst96_15/T/IDEDistributionOptionThinning.~~~iSjBnA/Payload/MAVSDK_Swift_Example.app/Frameworks/libavcodec.a (architecture arm64)
/var/folders/fk/9kh981v9165g2t1yh3lbrkcst96_15/T/IDEDistributionOptionThinning.~~~iSjBnA/Payload/MAVSDK_Swift_Example.app/Frameworks/libavcodec.a(012v.o) (architecture arm64):
Mach header
      magic  cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64    ARM64        ALL  0x00      OBJECT     5        856 SUBSECTIONS_VIA_SYMBOLS
Load command 0
.....
```

Would you have an idea what that means? We thought that there were maybe non-arm64 symbols in `libavcodec.a`, but we only found arm64 symbols there...

**Comment by kewlbear** [comment]
The open source app you mentioned had some problem of its own uploading to App Store.  So I tried with my YoutubeDL app.  I have successfully uploaded it to App Store with Xcode 12.5 beta 3.
